import { AsyncAPI2, AsyncAPI3 } from '../../../target-specs.ts';

const documentation = [
  {
    target: 'headers',
    docs: '[Schema Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#schemaObject) \\| [Reference Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#referenceObject)\n\\\n\\\n**Optional**. A Schema object containing the definitions for Anypoint MQ-specific headers (so-called protocol headers). This schema MUST be of type `object` and have a `properties` key. Examples of Anypoint MQ protocol headers are `messageId` and `messageGroupId`.',
    targetSpecs: AsyncAPI2,
  },
  {
    target: 'headers',
    docs: '[Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject) \\| [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject)\n\\\n\\\n**Optional**. A Schema object containing the definitions for Anypoint MQ-specific headers (so-called protocol headers). This schema MUST be of type `object` and have a `properties` key. Examples of Anypoint MQ protocol headers are `messageId` and `messageGroupId`.',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'bindingVersion',
    docs: '**Optional**, defaults to `0.1.0`. The version of this binding.',
  },
  {
    docs: "#### [Message Binding Object](https://github.com/asyncapi/bindings/tree/master/anypointmq#message-binding-object)\n\nThe Anypoint MQ [Message Binding Object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#message-bindings-object) is defined by a [JSON Schema](https://github.com/asyncapi/bindings/blob/master/anypointmq/json_schemas/message.json), which defines these fields:\n\nField Name | Type | Description\n---|:---:|---\n`headers`               | [Schema Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#schemaObject) \\| [Reference Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#referenceObject) | **Optional**. A Schema object containing the definitions for Anypoint MQ-specific headers (so-called protocol headers). This schema MUST be of type `object` and have a `properties` key. Examples of Anypoint MQ protocol headers are `messageId` and `messageGroupId`.\n`bindingVersion` | string | **Optional**, defaults to `0.1.0`. The version of this binding.\n\nNote that application headers must be specified in the [`headers` field of the standard Message Object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObjectHeaders) and are transmitted in the [`properties` section of the Anypoint MQ message](https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-broker/).\nIn contrast, protocol headers such as `messageId` must be specified in the [`headers` field of the message binding object](https://github.com/asyncapi/bindings/tree/master/anypointmq#messageBindingObjectHeaders) and are transmitted in the [`headers` section of the Anypoint MQ message](https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-broker/).\n\n### Examples\n\nThe following example shows a `channels` object with two channels, each having one operation (`subscribe` or `publish`) with one message. Only the message of the `subscribe` operation has a message binding object for `anypointmq`:\n\n\n\\\nYAML\n```yaml\nchannels:\n  user/signup:\n    publish:\n      message:\n        #...\n  user/signedup:\n    subscribe:\n      message:\n        headers:\n          type: object\n          properties:\n            correlationId:\n              description: Correlation ID set by application\n              type: string\n        payload:\n          type: object\n          properties:\n            #...\n        correlationId:\n          description: Correlation ID is specified as a header and transmitted in the Anypoint MQ message properties section\n          location:    $message.header#/correlationId\n        bindings:\n          anypointmq:\n            headers:\n              type: object\n              properties:\n                messageId:\n                  type: string\n            bindingVersion: '0.1.0'\n```",
    targetSpecs: AsyncAPI2,
  },
  {
    docs: "#### [Message Binding Object](https://github.com/asyncapi/bindings/tree/master/anypointmq#message-binding-object)\n\nThe Anypoint MQ [Message Binding Object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#message-bindings-object) is defined by a [JSON Schema](https://github.com/asyncapi/bindings/blob/master/anypointmq/json_schemas/message.json), which defines these fields:\n\nField Name | Type | Description\n---|:---:|---\n`headers`               | [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject) \\| [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) | **Optional**. A Schema object containing the definitions for Anypoint MQ-specific headers (so-called protocol headers). This schema MUST be of type `object` and have a `properties` key. Examples of Anypoint MQ protocol headers are `messageId` and `messageGroupId`.\n`bindingVersion` | string | **Optional**, defaults to `0.1.0`. The version of this binding.\n\nNote that application headers must be specified in the [`headers` field of the standard Message Object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObjectHeaders) and are transmitted in the [`properties` section of the Anypoint MQ message](https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-broker/).\nIn contrast, protocol headers such as `messageId` must be specified in the [`headers` field of the message binding object](https://github.com/asyncapi/bindings/tree/master/anypointmq#messageBindingObjectHeaders) and are transmitted in the [`headers` section of the Anypoint MQ message](https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-broker/).\n\n### Examples\n\nThe following example shows a `channels` object with two channels, each having one operation (`subscribe` or `publish`) with one message. Only the message of the `subscribe` operation has a message binding object for `anypointmq`:\n\n\n\\\nYAML\n```yaml\nchannels:\n  user/signup:\n    publish:\n      message:\n        #...\n  user/signedup:\n    subscribe:\n      message:\n        headers:\n          type: object\n          properties:\n            correlationId:\n              description: Correlation ID set by application\n              type: string\n        payload:\n          type: object\n          properties:\n            #...\n        correlationId:\n          description: Correlation ID is specified as a header and transmitted in the Anypoint MQ message properties section\n          location:    $message.header#/correlationId\n        bindings:\n          anypointmq:\n            headers:\n              type: object\n              properties:\n                messageId:\n                  type: string\n            bindingVersion: '0.1.0'\n```",
    targetSpecs: AsyncAPI3,
  },
];
export default documentation;
