import {
  ApidomCompletionItem,
  CompletionFormat,
  CompletionType,
} from '../../../apidom-language-types';

const completion: ApidomCompletionItem[] = [
  {
    label: '$ref',
    insertText: '\\$ref',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'A reference to a Callback.',
    },
  },
  {
    label: '$url',
    insertText: "'\\$url'",
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request URL',
    },
  },
  {
    label: '$method',
    insertText: "'\\$method'",
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'HTTP Method',
    },
  },
  {
    label: '$statusCode',
    insertText: "'\\$statusCode'",
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Status Code',
    },
  },
  {
    label: '$request.path...',
    insertText: '\\$request.path.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Path',
    },
  },
  {
    label: '$request.query...',
    insertText: '\\$request.query.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Query',
    },
  },
  {
    label: '$request.header...',
    insertText: '\\$request.header.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Header',
    },
  },
  {
    label: '$request.header...',
    insertText: '\\$request.header.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Header',
    },
  },
  {
    label: '$request.body',
    insertText: "'\\$request.body'",
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Body',
    },
  },
  {
    label: '$request.body#/...',
    insertText: '\\$request.body#/.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Request Body..',
    },
  },
  {
    label: '$response.path...',
    insertText: '\\$response.path.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Path',
    },
  },
  {
    label: '$response.query...',
    insertText: '\\$response.query.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Query',
    },
  },
  {
    label: '$response.header...',
    insertText: '\\$response.header.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Header',
    },
  },
  {
    label: '$response.header...',
    insertText: '\\$response.header.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Header',
    },
  },
  {
    label: '$response.body',
    insertText: "'\\$response.body'",
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Body',
    },
  },
  {
    label: '$response.body#/...',
    insertText: '\\$response.body#/.',
    kind: 14,
    format: CompletionFormat.PARTIAL_KEY_QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'Response Body..',
    },
  },
];

export default completion;
