version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5


