version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "tree-sitter-cli" # https://github.com/swagger-api/apidom/issues/1