import { DocumentationMeta } from '../../../../../apidom-language-types.ts';
import { JSONSchema202012 } from '../../target-specs.ts';

const documentation: DocumentationMeta[] = [
  {
    target: '$id',
    docs: 'The "$id" keyword identifies a schema resource with its [canonical [RFC6596]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC6596) URI.\n\\\n\\\nNote that this URI is an identifier and not necessarily a network locator. In the case of a network-addressable URL, a schema need not be downloadable from its canonical URI.\n\\\n\\\nIf present, the value for this keyword MUST be a string, and MUST represent a valid [URI-reference [RFC3986]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC3986). This URI-reference SHOULD be normalized, and MUST resolve to an [absolute-URI [RFC3986]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC3986) (without a fragment), or to a URI with an empty fragment.\n\\\n\\\nThe empty fragment form is NOT RECOMMENDED and is retained only for backwards compatibility, and because the application/schema+json media type defines that a URI with an empty fragment identifies the same resource as the same URI with the fragment removed. However, since this equivalence is not part of the [RFC 3986 normalization process [RFC3986]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC3986), implementers and schema authors cannot rely on generic URI libraries understanding it.\n\\\n\\\nTherefore, "$id" MUST NOT contain a non-empty fragment, and SHOULD NOT contain an empty fragment. The absolute-URI form MUST be considered the canonical URI, regardless of the presence or absence of an empty fragment. An empty fragment is currently allowed because older meta-schemas have an empty fragment in their $id (or previously, id). A future draft may outright forbid even empty fragments in "$id".\n\\\n\\\nThe absolute-URI also serves as the base URI for relative URI-references in keywords within the schema resource, in accordance with [RFC 3986 section 5.1.1 [RFC3986]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC3986) regarding base URIs embedded in content.\n\\\n\\\nThe presence of "$id" in a subschema indicates that the subschema constitutes a distinct schema resource within a single schema document. Furthermore, in accordance with [RFC 3986 section 5.1.2 [RFC3986]](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#RFC3986) regarding encapsulating entities, if an "$id" in a subschema is a relative URI-reference, the base URI for resolving that reference is the URI of the parent schema resource.\n\\\n\\\nIf no parent schema object explicitly identifies itself as a resource with "$id", the base URI is that of the entire document, as established by the steps given in the [previous section. (Section 9.1.1)](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#initial-base)',
    targetSpecs: JSONSchema202012,
  },
];

export default documentation;
