const symbols = [
  'parameter',
  'api-version',
  'spec-version',
  'info',
  'operation',
  'components',
  'components-parameters',
  'components-schemas',
  'schema',
  'server',
  'servers',
  'channelItem',
  'channels',
  'reference-element',
  'reference-value',
  'components-messages',
  'channel-binding',
  'contact',
  'identifier',
  'license',
  'message',
];

export default symbols;
