import {
  ApidomCompletionItem,
  CompletionFormat,
  CompletionType,
} from '../../../apidom-language-types';

const completion: ApidomCompletionItem[] = [
  {
    label: 'application/json',
    insertText: 'application/json',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0001',
  },
  {
    label: 'application/xml',
    insertText: 'application/xml',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0002',
  },
  {
    label: 'application/yaml',
    insertText: 'application/yaml',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0003',
  },
  {
    label: 'application/x-www-form-urlencoded',
    insertText: 'application/x-www-form-urlencoded',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0004',
  },
  {
    label: 'application/octet-stream',
    insertText: 'application/octet-stream',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0005',
  },
  {
    label: 'application/pdf',
    insertText: 'application/pdf',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0006',
  },
  {
    label: 'application/zip',
    insertText: 'application/zip',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0007',
  },
  {
    label: 'application/gzip',
    insertText: 'application/gzip',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0008',
  },
  {
    label: 'multipart/form-data',
    insertText: 'multipart/form-data',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0009',
  },
  {
    label: 'text/plain',
    insertText: 'text/plain',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0010',
  },
  {
    label: 'text/plain;charset=utf-8',
    insertText: 'text/plain;charset=utf-8',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0011',
  },
  {
    label: 'text/html',
    insertText: 'text/html',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0011',
  },
  {
    label: 'text/xml',
    insertText: 'text/xml',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0013',
  },
  {
    label: 'text/csv',
    insertText: 'text/csv',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0014',
  },
  {
    label: 'text/javascript',
    insertText: 'text/javascript',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0015',
  },
  {
    label: 'text/css',
    insertText: 'text/css',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0016',
  },
  {
    label: 'image/png',
    insertText: 'image/png',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0017',
  },
  {
    label: 'image/jpeg',
    insertText: 'image/jpeg',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0018',
  },
  {
    label: 'image/gif',
    insertText: 'image/gif',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0019',
  },
  {
    label: 'image/bmp',
    insertText: 'image/bmp',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    sortText: '0020',
  },
];

export default completion;
