import {
  ApidomCompletionItem,
  CompletionFormat,
  CompletionType,
} from '../../../apidom-language-types.ts';
import { AsyncAPI3 } from '../target-specs.ts';

const completion: ApidomCompletionItem[] = [
  {
    label: 'schemaFormat',
    insertText: 'schemaFormat',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '**REQUIRED**. A string containing the name of the schema format that is used to define the information. If schemaFormat is missing, it MUST default to application/vnd.aai.asyncapi+json;version={{asyncapi}} where {{asyncapi}} matches the [AsyncAPI Version String](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SVersionString). In such a case, this would make the Multi Format Schema Object equivalent to the [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject). When using [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) within the schema, the schemaFormat of the resource being referenced MUST match the schemaFormat of the schema that contains the initial reference. For example, if you reference Avro schema, then schemaFormat of referencing resource and the resource being reference MUST match.\\\n\\\nCheck out the [supported schema formats table](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaFormatTable) for more information. Custom values are allowed but their implementation is OPTIONAL. A custom value MUST NOT refer to one of the schema formats listed in the [table](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaFormatTable).\\\n\\\nWhen using [Reference Objects](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) within the schema, the schemaFormat of the referenced resource MUST match the schemaFormat of the schema containing the reference.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'schema',
    insertText: 'schema',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '**REQUIRED**. Definition of the message payload. It can be of any type but defaults to [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject). It MUST match the schema format defined in [schemaFormat](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaObjectSchemaFormat), including the encoding type. E.g., Avro should be inlined as either a YAML or JSON object instead of as a string to be parsed as YAML or JSON. Non-JSON-based schemas (e.g., Protobuf or XSD) MUST be inlined as a string.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=3.0.0',
    insertText: 'application/vnd.aai.asyncapi;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0001',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=3.0.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0002',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=3.0.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0003',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/schema+json;version=draft-07',
    insertText: 'application/schema+json;version=draft-07',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0004',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/schema+yaml;version=draft-07',
    insertText: 'application/schema+yaml;version=draft-07',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0005',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro;version=1.9.0',
    insertText: 'application/vnd.apache.avro;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0006',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro+json;version=1.9.0',
    insertText: 'application/vnd.apache.avro+json;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0007',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro+yaml;version=1.9.0',
    insertText: 'application/vnd.apache.avro+yaml;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0008',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi;version=3.0.0',
    insertText: 'application/vnd.oai.openapi;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0009',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi+json;version=3.0.0',
    insertText: 'application/vnd.oai.openapi+json;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0010',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi+yaml;version=3.0.0',
    insertText: 'application/vnd.oai.openapi+yaml;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0011',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/raml+yaml;version=1.0',
    insertText: 'application/raml+yaml;version=1.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0012',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.google.protobuf;version=2',
    insertText: 'application/vnd.google.protobuf;version=2',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0013',
    targetSpecs: AsyncAPI3,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.google.protobuf;version=3',
    insertText: 'application/vnd.google.protobuf;version=3',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0014',
    targetSpecs: AsyncAPI3,
  },
];

export default completion;
