import { DiagnosticSeverity } from 'vscode-languageserver-types';

import ApilintCodes from '../../../codes';
import { LinterMeta } from '../../../../apidom-language-types';
import { OpenAPI31 } from '../../../openapi/target-specs';

// eslint-disable-next-line @typescript-eslint/naming-convention
const missingCoreFieldsOpenAPI3_1Lint: LinterMeta = {
  code: ApilintCodes.SCHEMA_MISSING_CORE_FIELDS,
  source: 'apilint',
  message: 'Schema does not include any Schema Object keywords',
  severity: DiagnosticSeverity.Hint,
  linterFunction: 'existAnyOfFields',
  linterParams: [
    [
      '$ref',
      '$schema',
      '$id',
      '$vocabulary',
      '$anchor',
      '$dynamicAnchor',
      '$defs',
      '$comment',
      'if',
      'then',
      'else',
      'dependentSchemas',
      'prefixItems',
      'contains',
      'patternProperties',
      'propertyNames',
      'unevaluatedProperties',
      'unevaluatedItems',
      'const',
      'maxContains',
      'minContains',
      'dependencies',
      'dependentRequired',
      'examples',
      'contentEncoding',
      'contentMediaType',
      'contentSchema',
      'definitions',
      'multipleOf',
      'maximum',
      'exclusiveMaximum',
      'minimum',
      'exclusiveMinimum',
      'maxLength',
      'minLength',
      'pattern',
      'additionalItems',
      'items',
      'maxItems',
      'minItems',
      'uniqueItems',
      'maxProperties',
      'minProperties',
      'required',
      'properties',
      'additionalProperties',
      'enum',
      'type',
      'allOf',
      'anyOf',
      'oneOf',
      'not',
      'title',
      'description',
      'default',
      'format',
      'readOnly',
      'discriminator',
      'externalDocs',
      'writeOnly',
      'xml',
      'example',
      'deprecated',
    ],
    true,
  ],
  marker: 'key',
  targetSpecs: OpenAPI31,
  conditions: [
    {
      function: 'apilintElementOrClass',
      params: [['schema']],
    },
  ],
};

export default missingCoreFieldsOpenAPI3_1Lint;
