import {
  ApidomCompletionItem,
  CompletionFormat,
  CompletionType,
} from '../../../apidom-language-types.ts';
import { AsyncAPI3 } from '../target-specs.ts';

const completion: ApidomCompletionItem[] = [
  {
    label: 'asyncapi',
    insertText: 'asyncapi',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[AsyncAPI Version String](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SVersionString)\n\\\n\\\n**REQUIRED.** Specifies the AsyncAPI Specification version being used. It can be used by tooling Specifications and clients to interpret the version. The structure shall be `major`.`minor`.`patch`, where `patch` versions _must_ be compatible with the existing `major`.`minor` tooling. Typically patch versions will be introduced to address errors in the documentation, and tooling should typically be compatible with the corresponding `major`.`minor` (1.0.*). Patch versions will correspond to patches of this document.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'id',
    insertText: 'id',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Identifier](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SIdString)\n\\\n\\\nIdentifier of the [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication) the AsyncAPI document is defining. This field represents a unique universal identifier of the [application](#definitionsApplication) the AsyncAPI document is defining. It must conform to the URI format, according to [RFC3986](https://tools.ietf.org/html/rfc3986).\n\\\n\\\nIt is RECOMMENDED to use a [URN](https://tools.ietf.org/html/rfc8141) to globally and uniquely identify the application during long periods of time, even after it becomes unavailable or ceases to exist.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'info',
    insertText: 'info',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Info Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#infoObject)\n\\\n\\\n**REQUIRED.** Provides metadata about the API. The metadata can be used by the clients if needed.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'servers',
    insertText: 'servers',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Servers Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serversObject)\n\\\n\\\nProvides connection details of servers. The Servers Object is a map of [Server Objects](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject).',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'defaultContentType',
    insertText: 'defaultContentType',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        "[Default Content Type](https://www.asyncapi.com/docs/reference/specification/v3.0.0#defaultContentTypeString)\n\\\n\\\nDefault content type to use when encoding/decoding a message's payload.\n\\\n\\\nIt's a string representing the default content type to use when encoding/decoding a message's payload. The value MUST be a specific media type (e.g. `application/json`). This value MUST be used by schema parsers when the [contentType](https://www.asyncapi.com/docs/reference/specification/v3.0.0#messageObjectContentType) property is omitted.\n\nIn case a message can't be encoded/decoded using this value, schema parsers MUST use their default content type.",
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'channels',
    insertText: 'channels',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Channels Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#channelsObject)\n\\\n\\\nThe channels used by this [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication).',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'operations',
    insertText: 'operations',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Operations Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationsObject)\n\\\n\\\nThe operations this [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication) MUST implement.',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'components',
    insertText: 'components',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Components Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#componentsObject)\n\\\n\\\nAn element to hold various reusable objects for the specification. Everything that is defined inside this object represents a resource that MAY or MAY NOT be used in the rest of the document and MAY or MAY NOT be used by the implemented [Application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication).',
    },
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/json',
    insertText: 'application/json',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0001',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/xml',
    insertText: 'application/xml',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0002',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/yaml',
    insertText: 'application/yaml',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0003',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/x-www-form-urlencoded',
    insertText: 'application/x-www-form-urlencoded',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0004',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/octet-stream',
    insertText: 'application/octet-stream',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0005',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/pdf',
    insertText: 'application/pdf',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0006',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/zip',
    insertText: 'application/zip',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0007',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'application/gzip',
    insertText: 'application/gzip',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0008',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'multipart/form-data',
    insertText: 'multipart/form-data',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0009',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/plain',
    insertText: 'text/plain',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0010',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/plain;charset=utf-8',
    insertText: 'text/plain;charset=utf-8',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0011',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/html',
    insertText: 'text/html',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0012',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/xml',
    insertText: 'text/xml',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0013',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/csv',
    insertText: 'text/csv',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0014',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/javascript',
    insertText: 'text/javascript',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0015',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'text/css',
    insertText: 'text/css',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0016',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'image/png',
    insertText: 'image/png',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0017',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'image/jpeg',
    insertText: 'image/jpeg',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0018',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'image/gif',
    insertText: 'image/gif',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0019',
    targetSpecs: AsyncAPI3,
  },
  {
    label: 'image/bmp',
    insertText: 'image/bmp',
    kind: 12,
    target: 'defaultContentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0020',
    targetSpecs: AsyncAPI3,
  },
];

export default completion;
