import { AsyncAPI3 } from '../target-specs.ts';

const documentation = [
  {
    docs: "#### [AsyncAPI Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SObject)\n\nThis is the root object of the [AsyncAPI document](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsAsyncAPIDocument).\n\n##### Fixed Fields\n\nField Name | Type | Description\n---|:---:|---\nasyncapi | [AsyncAPI Version String](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SVersionString) | **REQUIRED**. Specifies the AsyncAPI Specification version being used. It can be used by tooling Specifications and clients to interpret the version. The structure shall be `major`.`minor`.`patch`, where `patch` versions _must_ be compatible with the existing `major`.`minor` tooling. Typically patch versions will be introduced to address errors in the documentation, and tooling should typically be compatible with the corresponding `major`.`minor` (1.0.*). Patch versions will correspond to patches of this document.\nid | [Identifier](https://www.asyncapi.com/docs/reference/specification/v3.0.0#A2SIdString) | Identifier of the [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication) the AsyncAPI document is defining.\ninfo | [Info Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#infoObject) | **REQUIRED**. Provides metadata about the API. The metadata can be used by the clients if needed.\nservers | [Servers Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serversObject) | Provides connection details of servers.\ndefaultContentType | [Default Content Type](https://www.asyncapi.com/docs/reference/specification/v3.0.0#defaultContentTypeString) | Default content type to use when encoding/decoding a message's payload.\nchannels | [Channels Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#channelsObject) | The channels used by this [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication).\noperations | [Operations Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationsObject) | The operations this [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication) MUST implement.\ncomponents | [Components Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#componentsObject) | An element to hold various reusable objects for the specification. Everything that is defined inside this object represents a resource that MAY or MAY NOT be used in the rest of the document and MAY or MAY NOT be used by the implemented [Application](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication).",
    targetSpecs: AsyncAPI3,
  },
];

export default documentation;
