const openAPI2Symbols = [
  'contact',
  'definitions',
  'example',
  'externalDocumentation',
  'header',
  'headers',
  'info',
  'items',
  'license',
  'operation',
  'parameter',
  'parametersDefinitions',
  'pathItem',
  'paths',
  'reference',
  'JSONReference',
  'reference-value',
  'response',
  'responses',
  'responsesDefinitions',
  'schema',
  'scopes',
  'security',
  'securityDefinitions',
  'securityRequirement',
  'securityScheme',
  'swagger',
  'swagger-consumes',
  'swagger-consumes',
  'swagger-tags',
  'swaggerVersion',
  'tag',
  'xml',
  'spec-version',
  'api-version',
  'httpMethod',
];

const openAPI3symbols = [
  'parameter',
  'api-version',
  'spec-version',
  'info',
  'operation',
  'pathItem',
  'components',
  'components-parameters',
  'components-schemas',
  'paths',
  'requestBody',
  'response',
  'responses',
  'schema',
  'server',
  'servers',
  'reference-element',
  'reference-value',
  'contact',
  'httpMethod',
  'license',
  'security',
];

const symbols = [...openAPI2Symbols, ...openAPI3symbols];

export default symbols;
