import { AsyncAPI2, AsyncAPI3 } from '../target-specs.ts';

const documentation = [
  {
    docs: '#### [Servers Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#serversObject)\n\nThe Servers Object is a map of [Server Objects](https://www.asyncapi.com/docs/reference/specification/v2.6.0#serverObject).\n\n##### Patterned Fields\n\nField Pattern | Type | Description\n---|:---:|---\n`^[A-Za-z0-9_\\-]+$` | [Server Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#serverObject) | The definition of a server this application MAY connect to.\n\n##### Servers Object Example\n\n\n\\\nJSON\n```json\n{\n  "production": {\n    "url": "development.gigantic-server.com",\n    "description": "Development server",\n    "protocol": "kafka",\n    "protocolVersion": "1.0.0"\n  }\n}\n```\n\n\n\\\nYAML\n```yaml\nproduction:\n  url: development.gigantic-server.com\n  description: Development server\n  protocol: kafka\n  protocolVersion: \'1.0.0\'\n```',
    targetSpecs: AsyncAPI2,
  },
  {
    docs: '#### [Servers Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serversObject)\n\nThe Servers Object is a map of [Server Objects](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject).\n\n##### Patterned Fields\n\nField Pattern | Type | Description\n---|:---:|---\n`^[A-Za-z0-9_\\-]+$` | [Server Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject) \\| [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) | The definition of a server this application MAY connect to.\n\n##### Servers Object Example\n\n\n\\\nJSON\n```json\n{\n  "development": {\n    "host": "localhost:5672",\n    "description": "Development AMQP broker.",\n    "protocol": "amqp",\n    "protocolVersion": "0-9-1",\n    "tags": [\n      { \n        "name": "env:development",\n        "description": "This environment is meant for developers to run their own tests."\n      }\n    ]\n  },\n  "staging": {\n    "host": "rabbitmq-staging.in.mycompany.com:5672",\n    "description": "RabbitMQ broker for the staging environment.",\n    "protocol": "amqp",\n    "protocolVersion": "0-9-1",\n    "tags": [\n      { \n        "name": "env:staging",\n        "description": "This environment is a replica of the production environment."\n      }\n    ]\n  },\n  "production": {\n    "host": "rabbitmq.in.mycompany.com:5672",\n    "description": "RabbitMQ broker for the production environment.",\n    "protocol": "amqp",\n    "protocolVersion": "0-9-1",\n    "tags": [\n      { \n        "name": "env:production",\n        "description": "This environment is the live environment available for final users."\n      }\n    ]\n  }\n}\n```\n\n\n\\\nYAML\n```yaml\ndevelopment:\n  host: localhost:5672\n  description: Development AMQP broker.\n  protocol: amqp\n  protocolVersion: 0-9-1\n  tags:\n    - name: env:development\n      description: This environment is meant for developers to run their own tests.\nstaging:\n  host: rabbitmq-staging.in.mycompany.com:5672\n  description: RabbitMQ broker for the staging environment.\n  protocol: amqp\n  protocolVersion: 0-9-1\n  tags:\n    - name: env:staging\n      description: This environment is a replica of the production environment.\nproduction:\n  host: rabbitmq.in.mycompany.com:5672\n  description: RabbitMQ broker for the production environment.\n  protocol: amqp\n  protocolVersion: 0-9-1\n  tags:\n    - name: env:production\n      description: This environment is the live environment available for final users.\n```',
    targetSpecs: AsyncAPI3,
  },
];
export default documentation;
