const documentation = [
  {
    docs: '#### [Paths Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#pathsObject)\n\nHolds the relative paths to the individual endpoints and their operations. The path is appended to the URL from the [`Server Object`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#serverObject) in order to construct the full URL. The Paths MAY be empty, due to [Access Control List (ACL) constraints](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#securityFiltering).\n\n##### Patterned Fields\n\nField Pattern | Type | Description\n---|:---:|---\n/{path} | [Path Item Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#pathItemObject) | A relative path to an individual endpoint. The field name MUST begin with a forward slash (`/`). The path is <em>appended</em> (no relative URL resolution) to the expanded URL from the [Server Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#serverObject) `url` field in order to construct the full URL. [Path templating](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#pathTemplating) is allowed. When matching URLs, concrete(non-templated) paths would be matched before their templated counterparts. Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical.In case of ambiguous matching, it is up to the tooling to decide which one to use.\n\n\nThis object MAY be extended with [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#specificationExtensions).\n\n##### Path Templating Matching\n\n\nAssuming the following paths, the concrete definition, `/pets/mine`, will be matched first if used:\n\n```\n  /pets/{petId}\n  /pets/mine\n```\n\nThe following paths are considered identical and invalid:\n\n```\n/pets/{petId}\n/pets/{name}\n```\n\nThe following may lead to ambiguous resolution:\n\n```\n/{entity}/me\n/books/{id}\n```',
    // docsRef:
    //   '#### [Servers Object](https://www.asyncapi.com/docs/specifications/v2.4.0#serversObject)\n\nThe Servers Object is a map of [Server Objects](https://www.asyncapi.com/docs/specifications/v2.4.0#serverObject).\n\n##### Patterned Fields\n\nField Pattern | Type | Description\n---|:---:|---\n`^[A-Za-z0-9_\\-]+$` | [Server Object](https://www.asyncapi.com/docs/specifications/v2.4.0#serverObject) | The definition of a server this application MAY connect to.\n\n##### Servers Object Example\n\n\n\\\nJSON\n```json\n{\n  "production": {\n    "url": "development.gigantic-server.com",\n    "description": "Development server",\n    "protocol": "kafka",\n    "protocolVersion": "1.0.0"\n  }\n}\n```\n\n\n\\\nYAML\n```yaml\nproduction:\n  url: development.gigantic-server.com\n  description: Development server\n  protocol: kafka\n  protocolVersion: \'1.0.0\'\n```',
  },
];

export default documentation;
