import {
  ApidomCompletionItem,
  CompletionFormat,
  CompletionType,
} from '../../../apidom-language-types';

const completion: ApidomCompletionItem[] = [
  {
    label: '$ref',
    insertText: '\\$ref',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'A reference to a message trait',
    },
  },
  {
    label: 'messageId',
    insertText: 'messageId',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        'Unique string used to identify the message. The id MUST be unique among all messages described in the API. The messageId value is **case-sensitive**. Tools and libraries MAY use the messageId to uniquely identify a message, therefore, it is RECOMMENDED to follow common programming naming conventions.',
    },
    targetSpecs: [
      { namespace: 'asyncapi', version: '2.4.0' },
      { namespace: 'asyncapi', version: '2.5.0' },
      { namespace: 'asyncapi', version: '2.6.0' },
    ],
  },
  {
    label: 'headers',
    insertText: 'headers',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Schema Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#schemaObject) &#124; [Reference Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#referenceObject) \\\n\\\nSchema definition of the application headers. Schema MUST be of type "object". It **MUST NOT** define the protocol headers.',
    },
  },
  {
    label: 'correlationId',
    insertText: 'correlationId',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Correlation ID Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#correlationIdObject) &#124; [Reference Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#referenceObject)\n\\\n\\\nDefinition of the correlation ID used for message tracing or matching.',
    },
  },
  {
    label: 'schemaFormat',
    insertText: 'schemaFormat',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        'A string containing the name of the schema format/language used to define the message payload. If omitted, implementations should parse the payload as a [Schema object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#schemaObject).',
    },
  },
  {
    label: 'contentType',
    insertText: 'contentType',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        "The content type to use when encoding/decoding a message's payload. The value MUST be a specific media type (e.g. `application/json`). When omitted, the value MUST be the one specified on the [defaultContentType](https://www.asyncapi.com/docs/reference/specification/v2.6.0#defaultContentTypeString) field.",
    },
  },
  {
    label: 'name',
    insertText: 'name',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'A machine-friendly name for the message.',
    },
  },
  {
    label: 'title',
    insertText: 'title',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'A human-friendly title for the message.',
    },
  },
  {
    label: 'summary',
    insertText: 'summary',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value: 'A short summary of what the message is about.',
    },
  },
  {
    label: 'description',
    insertText: 'description',
    kind: 14,
    format: CompletionFormat.QUOTED,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        'A verbose explanation of the message. [CommonMark syntax](https://spec.commonmark.org/) can be used for rich text representation.',
    },
  },
  {
    label: 'tags',
    insertText: 'tags',
    kind: 14,
    format: CompletionFormat.ARRAY,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Tags Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#tagsObject)\n\\\n\\\nA list of tags for API documentation control. Tags can be used for logical grouping of messages.',
    },
  },
  {
    label: 'externalDocs',
    insertText: 'externalDocs',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[External Documentation Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#externalDocumentationObject)\n\\\n\\\nAdditional external documentation for this message.',
    },
  },
  {
    label: 'bindings',
    insertText: 'bindings',
    kind: 14,
    format: CompletionFormat.OBJECT,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[Message Bindings Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageBindingsObject) | [Reference Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#referenceObject)\n\\\n\\\nA map where the keys describe the name of the protocol and the values describe protocol-specific definitions for the message.',
    },
  },
  {
    label: 'examples',
    insertText: 'examples',
    kind: 14,
    format: CompletionFormat.ARRAY,
    type: CompletionType.PROPERTY,
    insertTextFormat: 2,
    documentation: {
      kind: 'markdown',
      value:
        '[[Message Example Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageExampleObject)\\]\n\\\n\\\nList of examples.',
    },
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.6.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.6.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.6.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.6.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.6.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.6.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.6.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.6.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.6.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.5.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.5.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.5.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.5.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.5.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.5.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.5.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.5.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.5.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.4.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.4.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.4.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.4.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.4.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.4.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.4.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.4.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.4.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.3.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.3.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.3.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.3.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.3.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.3.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.3.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.3.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.3.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.2.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.2.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.2.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.2.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.2.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.2.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.2.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.2.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.2.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.1.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.1.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.1.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.1.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.1.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.1.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.1.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.1.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.1.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi;version=2.0.0',
    insertText: 'application/vnd.aai.asyncapi;version=2.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.0.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+json;version=2.0.0',
    insertText: 'application/vnd.aai.asyncapi+json;version=2.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.0.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.aai.asyncapi+yaml;version=2.0.0',
    insertText: 'application/vnd.aai.asyncapi+yaml;version=2.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    targetSpecs: [{ namespace: 'asyncapi', version: '2.0.0' }],
  },
  {
    target: 'schemaFormat',
    label: 'application/schema+json;version=draft-07',
    insertText: 'application/schema+json;version=draft-07',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/schema+yaml;version=draft-07',
    insertText: 'application/schema+yaml;version=draft-07',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro;version=1.9.0',
    insertText: 'application/vnd.apache.avro;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro+json;version=1.9.0',
    insertText: 'application/vnd.apache.avro+json;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.apache.avro+yaml;version=1.9.0',
    insertText: 'application/vnd.apache.avro+yaml;version=1.9.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi;version=3.0.0',
    insertText: 'application/vnd.oai.openapi;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi+json;version=3.0.0',
    insertText: 'application/vnd.oai.openapi+json;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/vnd.oai.openapi+yaml;version=3.0.0',
    insertText: 'application/vnd.oai.openapi+yaml;version=3.0.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    target: 'schemaFormat',
    label: 'application/raml+yaml;version=1.0',
    insertText: 'application/raml+yaml;version=1.0',
    kind: 12,
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
  },
  {
    label: 'application/json',
    insertText: 'application/json',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0001',
  },
  {
    label: 'application/xml',
    insertText: 'application/xml',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0002',
  },
  {
    label: 'application/yaml',
    insertText: 'application/yaml',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0003',
  },
  {
    label: 'application/x-www-form-urlencoded',
    insertText: 'application/x-www-form-urlencoded',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0004',
  },
  {
    label: 'application/octet-stream',
    insertText: 'application/octet-stream',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0005',
  },
  {
    label: 'application/pdf',
    insertText: 'application/pdf',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0006',
  },
  {
    label: 'application/zip',
    insertText: 'application/zip',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0007',
  },
  {
    label: 'application/gzip',
    insertText: 'application/gzip',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0008',
  },
  {
    label: 'multipart/form-data',
    insertText: 'multipart/form-data',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0009',
  },
  {
    label: 'text/plain',
    insertText: 'text/plain',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0010',
  },
  {
    label: 'text/plain;charset=utf-8',
    insertText: 'text/plain;charset=utf-8',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0011',
  },
  {
    label: 'text/html',
    insertText: 'text/html',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0012',
  },
  {
    label: 'text/xml',
    insertText: 'text/xml',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0013',
  },
  {
    label: 'text/csv',
    insertText: 'text/csv',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0014',
  },
  {
    label: 'text/javascript',
    insertText: 'text/javascript',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0015',
  },
  {
    label: 'text/css',
    insertText: 'text/css',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0016',
  },
  {
    label: 'image/png',
    insertText: 'image/png',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0017',
  },
  {
    label: 'image/jpeg',
    insertText: 'image/jpeg',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0018',
  },
  {
    label: 'image/gif',
    insertText: 'image/gif',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0019',
  },
  {
    label: 'image/bmp',
    insertText: 'image/bmp',
    kind: 12,
    target: 'contentType',
    format: CompletionFormat.QUOTED,
    type: CompletionType.VALUE,
    insertTextFormat: 2,
    sortText: '0020',
  },
];

export default completion;
