name: Release monorepo packages
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      HUSKY: 0 # disabled husky and lint staged; https://typicode.github.io/husky/#/?id=with-env-variables

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.8
          registry-url: https://npm.pkg.github.com/
          scope: "@swagger-api"
      - name: Install monorepo dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
      - name: Build monorepo
        run: npm run build
      - name: Check TypeScript types
        run: npm run typescript:check-types
      - name: Execute tests in monorepo
        run: npm run test
      - name: Version bump & GitHub release
        run: |
          git config user.email "swagger-bot@smartbear.com"
          git config user.name "swagger-bot"
          npx lerna version --no-private --yes
        env:
          GH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
      - name: Publish monorepo npm packages
        run: npx lerna publish from-package --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
