name: Release monorepo packages
on:
  workflow_dispatch:
    branches:
      - main

env:
  CPU_CORES: 2
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org
      - name: Install monorepo dependencies
        run: npm ci --engine-strict=false
      - name: Build monorepo
        run: npm run build
      - name: Check TypeScript types
        run: npm run typescript:check-types
      - name: Execute tests in monorepo
        run: npm run test
      - name: Version bump & GitHub release
        run: |
          git config user.email "swagger-bot@smartbear.com"
          git config user.name "swagger-bot"
          npx lerna version prerelease --preid beta --no-private --yes --force-publish
        env:
          GH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish monorepo npm packages
        run: npx lerna publish from-package --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync-lockfile:
    name: Sync lockfile
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org
      - name: Sync lockfile
        run: |
          git config user.email "swagger-bot@smartbear.com"
          git config user.name "swagger-bot"
          git pull --rebase origin main
          npm install
          git add package-lock.json
          git diff --cached --quiet || git commit -m "chore: sync lockfile"
          git push origin main
